CREATE TABLE BI_BEST_OP_SCORE (
    [COLLECTION NAME] NVARCHAR(255),
    [BEST_OPERATOR] NVARCHAR(255),
    [BEST_SCORE] FLOAT,
    [CATEGORY] NVARCHAR(50)
);


INSERT INTO BI_BEST_OP_SCORE (
    [COLLECTION NAME],
    [BEST_OPERATOR],
    [BEST_SCORE],
    [CATEGORY]
)
SELECT
    [CollectionName],
    [OPERATOR],
    MAX([TOTAL_SCORE]) AS BEST_SCORE,
    'TOTAL' AS CATEGORY
FROM BI_SCORES_TOTAL
WHERE [TOTAL_SCORE] = (
    SELECT MAX([TOTAL_SCORE])
    FROM BI_SCORES_TOTAL AS Sub
    WHERE Sub.[CollectionName] = BI_SCORES_TOTAL.[CollectionName]
)
GROUP BY
    [CollectionName], [OPERATOR]

UNION ALL

SELECT

    [CollectionName],
    [OPERATOR],
    MAX([TOTAL_DATA]) AS BEST_SCORE,
    'DATA' AS CATEGORY
FROM BI_SCORES_TOTAL
WHERE [TOTAL_DATA] = (
    SELECT MAX([TOTAL_DATA])
    FROM BI_SCORES_TOTAL AS Sub
    WHERE Sub.[CollectionName] = BI_SCORES_TOTAL.[CollectionName]
)
GROUP BY
     [CollectionName], [OPERATOR]

UNION ALL

SELECT
    [CollectionName],
    [OPERATOR],
    MAX([TOTAL_VOICE]) AS BEST_SCORE,
    'VOICE' AS CATEGORY
FROM BI_SCORES_TOTAL
WHERE [TOTAL_VOICE] = (
    SELECT MAX([TOTAL_VOICE])
    FROM BI_SCORES_TOTAL AS Sub
    WHERE Sub.[CollectionName] = BI_SCORES_TOTAL.[CollectionName]
)
GROUP BY
    [CollectionName], [OPERATOR]

order by CollectionName


